root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/mem-shots.exe ./main.go"
  bin = "./tmp/mem-shots.exe"
  delay = 1000
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  log = "air.log"
  poll = false
  poll_interval = 500
  stop_on_error = true
  send_interrupt = false
  kill_delay = 500
  rerun = false
  rerun_delay = 500
  args_bin = []

[log]
  main_only = false
  time = false

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true

